# This is a Docker Compose configuration for local use.

# Run all services:
# docker compose up --build --detach

services:
  api:
    build: . # See Dockerfile for more details
    restart: no
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8013:8000"
    volumes:
      - "./settings.yaml:/app/settings.yaml:ro" # Read-only settings file
      - "./client_secret.json:/app/client_secret.json:ro" # Read-only Google OAuth client_secret.json file
      - "./token.json:/app/token.json:ro" # Read-only Google OAuth token.json file

  db:
    # See more: https://hub.docker.com/_/mongo
    image: "mongo:8.0"
    restart: no
    ports:
      - "27017:27017"
    volumes:
      - "mongodb:/data/db"
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh 127.0.0.1:27017/db --quiet
      timeout: 5s
      start_period: 30s
      interval: 1m
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME:-mongoadmin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD:-secret}

volumes:
  mongodb:
